include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    avoid_unused_constructor_parameters: true
    prefer_final_locals: true
    unnecessary_parenthesis: true
